# Generated by Django 3.2.3 on 2021-05-27 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_novo_app', '0007_auto_20210526_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='sub_grupo',
            new_name='subgrupo_tar_id',
        ),
    ]
