# Generated by Django 3.2.3 on 2021-05-27 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_novo_app', '0008_rename_sub_grupo_tarefa_subgrupo_tar_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='subgrupo_tar_id',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='user',
        ),
    ]
