# Generated by Django 3.2.3 on 2021-05-27 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_novo_app', '0009_auto_20210527_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefa_grupos', to='todo_novo_app.grupos'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='subgrupo_tar_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefa_subgrupos', to='todo_novo_app.sub_grupos'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
