# Generated by Django 3.1.7 on 2021-05-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_novo_app', '0010_auto_20210527_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupos',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sub_grupos',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
